#!/usr/bin/env bash
# Auto-generated â€” run in Google Cloud Shell (Console terminal), not on Windows.
# If gcloud fails with 4003 / failed to connect to port 22: IAP cannot reach sshd yet.
# Fix: bash add_iap_ssh_firewall_and_tag_cloudshell.sh  (then wait ~60s). Still broken? bash diagnose_iap_ssh_cloudshell.sh
# Shared VPC: IAP rule may belong in the HOST project.
# Escapes: TITANORBIT_IAP_SSH_ALL_VMS=1 and/or TITANORBIT_IAP_SSH_PRIORITY0=1 bash add_iap_ssh_firewall_and_tag_cloudshell.sh
set -euo pipefail
PROJECT_ID="titan-orbit"
ZONE="us-central1-a"
INSTANCE_SSH="jason@titan-orbit-compute-engine"
SCRIPT_B64='c2V0IC1lCkVYRV9OQU1FPSIiCmlmIFsgLW4gIiIgXSAmJiBbIC1mICIvaG9tZS9qYXNvbi90aXRhbm9yYml0LXNlcnZlci9UaXRhbk9yYml0TGludXgxLyIgXTsgdGhlbgogIEVYRV9OQU1FPSIiCmVsaWYgWyAtZiAiL2hvbWUvamFzb24vdGl0YW5vcmJpdC1zZXJ2ZXIvVGl0YW5PcmJpdExpbnV4MS9UaXRhbk9yYml0U2VydmVyLng4Nl82NCIgXTsgdGhlbgogIEVYRV9OQU1FPVRpdGFuT3JiaXRTZXJ2ZXIueDg2XzY0CmVsaWYgWyAtZiAiL2hvbWUvamFzb24vdGl0YW5vcmJpdC1zZXJ2ZXIvVGl0YW5PcmJpdExpbnV4MS9UaXRhbk9yYml0U2VydmVyIiBdOyB0aGVuCiAgRVhFX05BTUU9VGl0YW5PcmJpdFNlcnZlcgplbHNlCiAgZWNobyAiTm8gVGl0YW5PcmJpdFNlcnZlciBvciBUaXRhbk9yYml0U2VydmVyLng4Nl82NCBpbiAvaG9tZS9qYXNvbi90aXRhbm9yYml0LXNlcnZlci9UaXRhbk9yYml0TGludXgxIjsgbHMgLWxhICIvaG9tZS9qYXNvbi90aXRhbm9yYml0LXNlcnZlci9UaXRhbk9yYml0TGludXgxIiB8fCB0cnVlOyBleGl0IDEKZmkKY2htb2QgK3ggIi9ob21lL2phc29uL3RpdGFub3JiaXQtc2VydmVyL1RpdGFuT3JiaXRMaW51eDEvJEVYRV9OQU1FIgplY2hvICdXMVZ1YVhSZERRcEVaWE5qY21sd2RHbHZiajFVYVhSaGJpQlBjbUpwZENCRVpXUnBZMkYwWldRZ1NHVmhaR3hsYzNNZ1UyVnlkbVZ5RFFwQlpuUmxjajF1WlhSM2IzSnJMVzl1YkdsdVpTNTBZWEpuWlhRTkNsZGhiblJ6UFc1bGRIZHZjbXN0YjI1c2FXNWxMblJoY21kbGRBMEtEUXBiVTJWeWRtbGpaVjBOQ2xSNWNHVTljMmx0Y0d4bERRcFZjMlZ5UFdwaGMyOXVEUXBYYjNKcmFXNW5SR2x5WldOMGIzSjVQUzlvYjIxbEwycGhjMjl1TDNScGRHRnViM0ppYVhRdGMyVnlkbVZ5TDFScGRHRnVUM0ppYVhSTWFXNTFlREVOQ2tWNFpXTlRkR0Z5ZEQwdmFHOXRaUzlxWVhOdmJpOTBhWFJoYm05eVltbDBMWE5sY25abGNpOVVhWFJoYms5eVltbDBUR2x1ZFhneEwxOWZWRWxVUVU1UFVrSkpWRjlGV0VWZlh5QXRZbUYwWTJodGIyUmxJQzF1YjJkeVlYQm9hV056SUMwdGJXRjRVR3hoZVdWeWN6MDJNQ0F0TFhObGNuWmxjbEJ2Y25ROU56YzNOeUF0TFhKbGJHRjVVSEp2ZEc5amIydzlkV1J3SUMwdGFYTk1ZWFJsYzNROU1TQXRiRzluUm1sc1pTQXZhRzl0WlM5cVlYTnZiaTkwYVhSaGJtOXlZbWwwTFhObGNuWmxjaTlVYVhSaGJrOXlZbWwwVEdsdWRYZ3hMMUJzWVhsbGNpNXNiMmNOQ2xKbGMzUmhjblE5WVd4M1lYbHpEUXBTWlhOMFlYSjBVMlZqUFRVTkNrdHBiR3hUYVdkdVlXdzlVMGxIU1U1VURRcFVhVzFsYjNWMFUzUnZjRk5sWXowek1BMEtEUXBiU1c1emRHRnNiRjBOQ2xkaGJuUmxaRUo1UFcxMWJIUnBMWFZ6WlhJdWRHRnlaMlYwRFFvPScgfCBiYXNlNjQgLWQgfCBzdWRvIHRlZSAvZXRjL3N5c3RlbWQvc3lzdGVtL3RpdGFub3JiaXQtc2VydmVyLnNlcnZpY2UgPi9kZXYvbnVsbApzdWRvIHNlZCAtaSAic3xfX1RJVEFOT1JCSVRfRVhFX198JEVYRV9OQU1FfGciIC9ldGMvc3lzdGVtZC9zeXN0ZW0vdGl0YW5vcmJpdC1zZXJ2ZXIuc2VydmljZQpzdWRvIGNobW9kIDY0NCAvZXRjL3N5c3RlbWQvc3lzdGVtL3RpdGFub3JiaXQtc2VydmVyLnNlcnZpY2UKc3VkbyBzeXN0ZW1jdGwgZGFlbW9uLXJlbG9hZApzdWRvIHN5c3RlbWN0bCBlbmFibGUgLS1ub3cgdGl0YW5vcmJpdC1zZXJ2ZXIuc2VydmljZQpzdWRvIHN5c3RlbWN0bCBzdGF0dXMgdGl0YW5vcmJpdC1zZXJ2ZXIuc2VydmljZSAtLW5vLXBhZ2VyIC1sIHwgc2VkIC1uICcxLDgwcCcKZWNobwplY2hvIFJlY2VudCBsb2c6CmlmIFsgLWYgIi9ob21lL2phc29uL3RpdGFub3JiaXQtc2VydmVyL1RpdGFuT3JiaXRMaW51eDEvUGxheWVyLmxvZyIgXTsgdGhlbiB0YWlsIC1uIDgwICIvaG9tZS9qYXNvbi90aXRhbm9yYml0LXNlcnZlci9UaXRhbk9yYml0TGludXgxL1BsYXllci5sb2ciOyBlbHNlIGVjaG8gIihubyBQbGF5ZXIubG9nIHlldCAtIFVuaXR5IG1heSBjcmVhdGUgaXQgc2hvcnRseSBhZnRlciBzdGFydHVwKSI7IGZp'

gcloud config set project "$PROJECT_ID"
gcloud compute ssh "$INSTANCE_SSH" \
  --project="$PROJECT_ID" \
  --zone="$ZONE" \
  --tunnel-through-iap \
  --strict-host-key-checking=no \
  --quiet \
  --command="echo ${SCRIPT_B64} | base64 -d | bash -s"
