using System;
using System.Collections.Generic;
using TitanOrbit.Core;
using UnityEngine;

namespace TitanOrbit.Data
{
    /// <summary>
    /// Team-colored theatrical thumbs for orbit-store support SKUs (drones, rockets, mines).
    /// Loaded from Resources/StoreItemPreviewCatalog. Glyphs remain the fallback when a sprite is missing.
    /// Generated by Titan Orbit → Store Items → Generate Theatrical Menu Previews.
    /// </summary>
    [CreateAssetMenu(fileName = "StoreItemPreviewCatalog", menuName = "Titan Orbit/Store Item Preview Catalog")]
    public class StoreItemPreviewCatalog : ScriptableObject
    {
        const string ResourcesName = "StoreItemPreviewCatalog";

        /// <summary>One store SKU plus optional per-team sprites.</summary>
        [Serializable]
        public class StoreItemPreviewEntry
        {
            public StoreItemType itemType;
            public Sprite menuPreviewSprite;
            public List<ShipFamilyTeamMenuPreview> teamMenuPreviewSprites = new List<ShipFamilyTeamMenuPreview>();
        }

        [Tooltip("One row per orbit-menu support item (fighter/shield/mining drone, rockets, mines).")]
        public List<StoreItemPreviewEntry> entries = new List<StoreItemPreviewEntry>();

        static StoreItemPreviewCatalog _cached;

        /// <summary>Loads the Resources catalog once per domain.</summary>
        public static StoreItemPreviewCatalog LoadDefault()
        {
            if (_cached != null)
                return _cached;
            _cached = Resources.Load<StoreItemPreviewCatalog>(ResourcesName);
            return _cached;
        }

        /// <summary>Team-aware theatrical sprite, or null so the store tile can show a glyph.</summary>
        public Sprite GetSprite(StoreItemType itemType, TeamManager.Team team)
        {
            StoreItemPreviewEntry entry = FindEntry(itemType);
            if (entry == null)
                return null;

            if (team != TeamManager.Team.None && entry.teamMenuPreviewSprites != null)
            {
                for (int i = 0; i < entry.teamMenuPreviewSprites.Count; i++)
                {
                    ShipFamilyTeamMenuPreview row = entry.teamMenuPreviewSprites[i];
                    if (row != null && row.team == team && row.sprite != null)
                        return row.sprite;
                }
            }

            return entry.menuPreviewSprite;
        }

        /// <summary>Finds or creates the row for this SKU (editor generator).</summary>
        public StoreItemPreviewEntry GetOrCreateEntry(StoreItemType itemType)
        {
            StoreItemPreviewEntry existing = FindEntry(itemType);
            if (existing != null)
                return existing;
            var created = new StoreItemPreviewEntry { itemType = itemType };
            if (entries == null)
                entries = new List<StoreItemPreviewEntry>();
            entries.Add(created);
            return created;
        }

        StoreItemPreviewEntry FindEntry(StoreItemType itemType)
        {
            if (entries == null)
                return null;
            for (int i = 0; i < entries.Count; i++)
            {
                if (entries[i] != null && entries[i].itemType == itemType)
                    return entries[i];
            }

            return null;
        }
    }
}
